name: Update Google Fonts

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-google-fonts:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install requests jsonschema
      
      - name: Update Google Fonts
        run: |
          python scripts/google-fonts-translator.py
        env:
          GOOGLE_FONTS_API_KEY: ${{ secrets.GOOGLE_FONTS_API_KEY }}
      
      - name: Validate sources
        run: |
          python schemas/validate-sources.py sources/google-fonts.json
      
      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet sources/google-fonts.json; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit changes
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add sources/google-fonts.json
          git commit -m "Update Google Fonts data [skip ci]"
      
      - name: Push changes
        if: steps.changes.outputs.changed == 'true'
        run: |
          git push
      
      - name: Create summary
        run: |
          echo "## Google Fonts Update Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ${{ steps.changes.outputs.changed == 'true' && 'Updated' || 'No changes' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Time**: $(date -u)" >> $GITHUB_STEP_SUMMARY
          if [ -f sources/google-fonts.json ]; then
            font_count=$(jq '.source_info.total_fonts' sources/google-fonts.json)
            echo "- **Total Fonts**: $font_count" >> $GITHUB_STEP_SUMMARY
          fi
