name: Update Nerd Fonts

on:
  schedule:
    - cron: '0 3 * * *'  # Daily at 3 AM UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-nerd-fonts:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install requests jsonschema
      
      - name: Update Nerd Fonts
        run: |
          python scripts/nerd-fonts-translator.py
      
      - name: Validate sources
        run: |
          python schemas/validate-sources.py sources/nerd-fonts.json
      
      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet sources/nerd-fonts.json; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit changes
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add sources/nerd-fonts.json
          git commit -m "Update Nerd Fonts data [skip ci]"
      
      - name: Push changes
        if: steps.changes.outputs.changed == 'true'
        run: |
          git push
      
      - name: Create summary
        run: |
          echo "## Nerd Fonts Update Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ${{ steps.changes.outputs.changed == 'true' && 'Updated' || 'No changes' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Time**: $(date -u)" >> $GITHUB_STEP_SUMMARY
          if [ -f sources/nerd-fonts.json ]; then
            font_count=$(jq '.source_info.total_fonts' sources/nerd-fonts.json)
            echo "- **Total Fonts**: $font_count" >> $GITHUB_STEP_SUMMARY
          fi
